plugins:
  - rubocop-rails
  - rubocop-minitest
  - rubocop-disable_syntax
  - rubocop-capybara

AllCops:
  TargetRubyVersion: 3.2
  NewCops: enable
  SuggestExtensions: false
  Exclude:
    - "vendor/**/*"
    - "gemfiles/**/*"

Layout/LineLength:
  Max: 100
Layout/IndentationConsistency:
  EnforcedStyle: indented_internal_methods

Lint/ConstantDefinitionInBlock:
  Exclude:
    - "test/**/*"

Metrics:
  Enabled: false

Style/DisableSyntax:
  DisableSyntax:
    - unless
    - and_or_not
    - numbered_parameters

Style/CaseEquality:
  Enabled: false
Style/Documentation:
  Enabled: false
Style/ClassAndModuleChildren:
  Enabled: false
Style/NegatedIf:
  Enabled: false

Minitest/EmptyLineBeforeAssertionMethods:
  Enabled: false
Minitest/MultipleAssertions:
  Enabled: false
